### ISSUE TITLE
Update consolidate.js

### ISSUE THREAD

**Issue by gunta** [jtangelder/template-html-loader#8]
Update consolidate.js to the latest version which includes jade->pug support.

Thank you!

**Comment by bornaeon** [comment]
Pug is supported in Consolidate.js [0.14.1](https://github.com/tj/consolidate.js/releases/tag/0.14.1)... Let's upgrade it to that version or even later one, shall we? :) ([here is the PR](https://github.com/jtangelder/template-html-loader/pull/11))

**Comment by jtangelder** [comment]
0
